In [1]:
#NumPy
### Load in NumPy(Import NumPy package)
import numpy as np

In [2]:
#ndarray object
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [3]:
print(type(a))

<class 'list'>


In [4]:
np_a = np.array(a)

In [5]:
print(np_a)

[1 2 3 4 5]


In [6]:
print(type(np_a))

<class 'numpy.ndarray'>


In [7]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

43.5 µs ± 704 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
a = np.arange(1000)
%timeit a**2

881 ns ± 222 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
#Creating arrays(Manually creating arrays)
#1-D
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [11]:
#print dimensions
a.ndim

1

In [12]:
#shape
a.shape

(4,)

In [13]:
#2-D
b = np.array([[0,2,3,5],[1,4,6,8]])
b

array([[0, 2, 3, 5],
       [1, 4, 6, 8]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 4)

In [16]:
#3-D
c = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
c

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [17]:
c.ndim

3

In [18]:
c.shape

(1, 3, 3)

In [20]:
#Creating NumPy arrays from a list
#we know how to create a list,right
my_list = [2,4,6]
my_list

[2, 4, 6]

In [21]:
np.array(my_list)

array([2, 4, 6])

In [22]:
# we can convert a matrix which is also a list to array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.array(my_matrix).shape

(3, 3)

In [26]:
#arange
#using arrange fucntion --->arrange is an array-valued version of the built-in python range function
a = np.arange(20) #0....n-1
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
x = np.arange(1,15,3) #start ,  end(exclusive), step
x

array([ 1,  4,  7, 10, 13])

In [30]:
#Using Linspace
a = np.linspace(1,10,5) #start, end, number of points
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
b = np.linspace(0,10,7)
b

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [33]:
#Zeros and ones
np.zeros(3)

array([0., 0., 0.])

In [34]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [35]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
c = np.ones((5,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
#create Identity matrix
x = np.eye(3) #Return a 2-D array with ones on the diagonal and zeros else where.
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
d = np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [44]:
#craete a array using diag function
x = np.diag([2,4,6,8])
x

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [46]:
np.diag(x) #Extract diagonal


array([2, 4, 6, 8])

In [50]:
#Randint-- Return random integers from start(inclusive) to (exclusive).
random_array = np.random.randint(1,110,5)
print(random_array)

[ 86  74  35  12 102]


In [53]:
#rand --Create an array of the given shape and populate it with random sample from a uniform distribution over [0,2).
a = np.random.rand(3)
a

array([0.4019361 , 0.63258896, 0.90503101])

In [1]:
import numpy as np

In [2]:
#randn -- Return a sample (or samples) form the "Standard normal" distribution. ***Gausian***
a = np.random.randn(100)
a

array([ 0.72417504,  1.06468234,  1.20406907,  0.71382112,  0.41837554,
       -3.21100443,  0.81290704, -0.89763082,  1.07333351, -0.76465176,
        1.53819023,  0.10968186,  0.20494211,  0.80392204,  0.89528067,
       -0.45123881,  0.05055476, -0.93740191,  0.259204  ,  0.75835532,
        0.126832  ,  0.87101062,  0.27892711, -0.07685659,  0.09751763,
        0.19466976,  0.21862255,  2.34186774, -0.40359009, -0.63292895,
       -0.34761071,  0.33669436,  1.12777148, -0.52310144, -0.37789535,
        1.14085399,  0.24790519,  1.07946574,  0.30018306, -1.21484044,
       -0.48955114,  1.43283478,  0.92967481,  0.6994258 , -0.2857283 ,
       -0.37945166, -0.61830444, -0.22465076,  0.09176014, -0.8228506 ,
       -0.66970683, -2.00318466,  0.08764467, -0.29807707,  0.41792423,
        1.00597388,  1.36801517, -0.59373735,  1.0220948 ,  2.82688078,
       -0.27900624,  0.69286995,  0.31603896, -0.04587594,  1.57066007,
       -0.04197144, -1.20669542, -1.24642307,  0.02858052,  0.41

In [3]:
#copy array
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [4]:
import numpy as np

In [11]:
#Reshape array
arr = np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [13]:
#Notice the two sets of brackets
a1 = arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("Shape of a: {}".format(a.shape))

[[1 2 3]
 [4 5 6]]
Shape of a: (2, 3)


In [15]:
#reshaping
b = a.reshape(3,2)
print(b)
print("Shape of b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
Shape of b: (3, 2)


In [16]:
#Transpose array
a = np.array([[2,4,6],[8,10,12]])
print("Shape: {}".format(a.shape))
print(a)

Shape: (2, 3)
[[ 2  4  6]
 [ 8 10 12]]


In [17]:
c = a.T
print(c)

[[ 2  8]
 [ 4 10]
 [ 6 12]]


In [18]:
a = np.array([[2,4,6],[8,10,12]])
a.ravel()

array([ 2,  4,  6,  8, 10, 12])

In [19]:
c.ravel()

array([ 2,  8,  4, 10,  6, 12])

In [22]:
#Sorting along an axix:
# axis=1 --> row and  axis=0 -->column
a= np.array([[5,3,1],[7,6,2]])
b= np.sort(a, axis=1)
b

array([[1, 3, 5],
       [2, 6, 7]])

In [23]:
#Add/Remove operations on a numpy array
a = np.array([4,7,8])
a = np.append(a,[2,4,5])
print('Numpy array after addition:',a)

Numpy array after addition: [4 7 8 2 4 5]


In [24]:
a = np.delete(a,2)
print('Numpy array after deletion of one element:',a)

Numpy array after deletion of one element: [4 7 2 4 5]


In [26]:
#Indexing
a = np.arange(3,15)
print(a)
print(a[5])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
8


In [27]:
#For multidimensional arrays, indexes are tuples of integers:
a = np.diag([2, 4, 6])
print(a)
print(a[2,1])

[[2 0 0]
 [0 4 0]
 [0 0 6]]
0


In [31]:
a[1,2] = 3 #assigning value
a

array([[2, 0, 0],
       [0, 4, 3],
       [0, 3, 3]])

In [32]:
a = np.arange(4,16)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
a[1:8:2] #[startindex: endindex(exclusive) : step]

array([ 5,  7,  9, 11])

In [34]:
#we can also combine assignment and slicing:
a = np.arange(20)
a[8:]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
a[5:] = 10
a

array([ 0,  1,  2, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10])

In [40]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [41]:
b[:: -1]

array([4, 3, 2, 1, 0])

In [50]:
a[5:]=b[::-1]

ValueError: could not broadcast input array from shape (5,) into shape (15,)

a

In [51]:
#Fancy Indexing
a = np.random.randint(0, 20, 5)
a

array([ 5,  2,  8, 14, 17])

In [6]:
 import array as a 

In [8]:
a[a % 2 == 0]

TypeError: unsupported operand type(s) for %: 'module' and 'int'

In [9]:
a[a % 2 == 0] = -1

TypeError: unsupported operand type(s) for %: 'module' and 'int'

In [11]:
import numpy as np

In [12]:
#Indexing with an array of integers
a = np.arange(0, 101, 10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [13]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [14]:
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200,  100])

In [16]:
#operation
#Basic Operations with Scalars
a = np.array([1, 4, 5, 6])
print(a)
print(a+1)


[1 4 5 6]
[2 5 6 7]


In [17]:
a ** 2

array([ 1, 16, 25, 36])

In [2]:
import numpy as np

In [8]:
#All arithmetic operates elementwise
b = np.ones(4) + 1
b


array([2., 2., 2., 2.])

In [7]:
a = np.ones(5) + 1
a

array([2., 2., 2., 2., 2.])

In [9]:
a - b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [10]:
a * b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [12]:
a = np.array([[2,3],[4,5],[6,7]])
b = np.array([[3,3],[3,3],[3,3]])

#adding a and b
print('Sum of a and b :\n', a+b)

Sum of a and b :
 [[ 5  6]
 [ 7  8]
 [ 9 10]]


In [13]:
#Multiply a and b - elementwise multiplication
print('product of a and b :\n',a*b)

product of a and b :
 [[ 6  9]
 [12 15]
 [18 21]]


In [14]:
#array multiplication
c = np.diag([1, 3, 5, 7])
print( c * c)

[[ 1  0  0  0]
 [ 0  9  0  0]
 [ 0  0 25  0]
 [ 0  0  0 49]]


In [15]:
#Matrix multiplication
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[3,3,1],[3,3,2],[3,3,3]])
print('Matrix multiplication: \n',np.matmul(a,b))

Matrix multiplication: 
 [[18 18 14]
 [45 45 32]
 [72 72 50]]


In [16]:
#Comparisions
a = np.array([1,2,3,4])
b = np.array([4,3,3,2])
a == b

array([False, False,  True, False])

In [17]:
a>b

array([False, False, False,  True])

In [20]:
np.array_equal(a,b)

False

In [21]:
np.array_equal(a, c)

False

In [22]:
#Logical Operations
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [23]:
np.logical_and(a,b)

array([ True, False, False, False])

In [24]:
#Transcendental functions
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [25]:
np.log(a)

C:\Users\srini\AppData\Local\Temp\ipykernel_19820\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [26]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [30]:
#Shape Mismatch
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [32]:
#Basic Reductions
#computing sums
x = np.array([1,2,3,5])
np.sum(x)

11

In [33]:
#Sum by rows and columns
x = np.array([[1,1],[3,3]])
x

array([[1, 1],
       [3, 3]])

In [34]:
x.sum(axis = 0)

array([4, 4])

In [36]:
x.sum(axis = 1)

array([2, 6])

In [39]:
#Other reductions
x = np.array([1,4,2])
x.min()

1

In [40]:
x.max()

4

In [41]:
x.argmin()

0

In [42]:
x.argmax()

1

In [47]:
#Statistics

normal_array = np.arange(0,10,1)
print('Array is ',format(normal_array))

##min
print('min element is ',np.min(normal_array))

##max
print('max element is ',np.max(normal_array))

##sum
print('sum of element in array is ',np.sum(normal_array))

##mean
print('mean of element in array is ',np.mean(normal_array))

##median
print('median of elements in array is ',np.median(normal_array))

##Sd
print('standard deviation of elements in array is ',np.std(normal_array))

Array is  [0 1 2 3 4 5 6 7 8 9]
min element is  0
max element is  9
sum of element in array is  45
mean of element in array is  4.5
median of elements in array is  4.5
standard deviation of elements in array is  2.8722813232690143
